import { Influencer, BrandCampaign, Interaction } from '@/types/matchmaking';

export const mockInfluencers: Influencer[] = [
  {
    id: 'inf-1',
    handle: '@fashionista_maya',
    platforms: ['Instagram', 'TikTok'],
    niches: ['Fashion', 'Lifestyle', 'Beauty'],
    audienceGeo: ['Mumbai', 'Delhi', 'Bangalore'],
    audienceAge: ['18-24', '25-34'],
    audienceGenderMix: { male: 25, female: 72, other: 3 },
    followers: 450000,
    avgViews: 85000,
    engagementRate: 4.2,
    contentQuality: 4.5,
    brandSafety: 4.8,
    pricePerPost: 25000,
    availability: true,
    pastBrands: ['Zara', 'H&M', 'Myntra'],
    fraudRisk: 0.05,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    bio: 'Fashion & lifestyle content creator. Collaborated with 50+ brands.'
  },
  {
    id: 'inf-2',
    handle: '@tech_reviewer_raj',
    platforms: ['YouTube', 'Instagram'],
    niches: ['Technology', 'Gadgets', 'Reviews'],
    audienceGeo: ['Bangalore', 'Hyderabad', 'Pune'],
    audienceAge: ['25-34', '35-44'],
    audienceGenderMix: { male: 78, female: 20, other: 2 },
    followers: 820000,
    avgViews: 145000,
    engagementRate: 3.8,
    contentQuality: 4.7,
    brandSafety: 4.9,
    pricePerPost: 45000,
    availability: true,
    pastBrands: ['Samsung', 'OnePlus', 'Amazon'],
    fraudRisk: 0.02,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    bio: 'Tech enthusiast reviewing latest gadgets and innovations.'
  },
  {
    id: 'inf-3',
    handle: '@fitness_guru_priya',
    platforms: ['Instagram', 'YouTube'],
    niches: ['Fitness', 'Health', 'Wellness'],
    audienceGeo: ['Delhi', 'Mumbai', 'Chennai'],
    audienceAge: ['18-24', '25-34', '35-44'],
    audienceGenderMix: { male: 45, female: 53, other: 2 },
    followers: 320000,
    avgViews: 62000,
    engagementRate: 5.1,
    contentQuality: 4.3,
    brandSafety: 5.0,
    pricePerPost: 18000,
    availability: true,
    pastBrands: ['Nike', 'Adidas', 'MyProtein'],
    fraudRisk: 0.03,
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    bio: 'Certified fitness trainer helping people achieve their health goals.'
  },
  {
    id: 'inf-4',
    handle: '@foodie_adventures',
    platforms: ['Instagram', 'TikTok', 'YouTube'],
    niches: ['Food', 'Travel', 'Lifestyle'],
    audienceGeo: ['Mumbai', 'Goa', 'Bangalore'],
    audienceAge: ['18-24', '25-34'],
    audienceGenderMix: { male: 42, female: 56, other: 2 },
    followers: 580000,
    avgViews: 98000,
    engagementRate: 4.6,
    contentQuality: 4.4,
    brandSafety: 4.6,
    pricePerPost: 32000,
    availability: false,
    pastBrands: ['Swiggy', 'Zomato', 'UberEats'],
    fraudRisk: 0.08,
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400',
    bio: 'Food blogger exploring culinary delights across India.'
  },
  {
    id: 'inf-5',
    handle: '@gaming_legend_arjun',
    platforms: ['YouTube', 'Twitch'],
    niches: ['Gaming', 'Entertainment', 'Technology'],
    audienceGeo: ['Bangalore', 'Delhi', 'Kolkata'],
    audienceAge: ['13-17', '18-24'],
    audienceGenderMix: { male: 85, female: 13, other: 2 },
    followers: 1200000,
    avgViews: 220000,
    engagementRate: 3.5,
    contentQuality: 4.6,
    brandSafety: 4.2,
    pricePerPost: 65000,
    availability: true,
    pastBrands: ['ASUS', 'Logitech', 'Red Bull'],
    fraudRisk: 0.04,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
    bio: 'Professional gamer and streamer with 1M+ subscribers.'
  },
  {
    id: 'inf-6',
    handle: '@beauty_by_sneha',
    platforms: ['Instagram', 'YouTube'],
    niches: ['Beauty', 'Makeup', 'Skincare'],
    audienceGeo: ['Delhi', 'Mumbai', 'Jaipur'],
    audienceAge: ['18-24', '25-34'],
    audienceGenderMix: { male: 15, female: 83, other: 2 },
    followers: 390000,
    avgViews: 71000,
    engagementRate: 4.9,
    contentQuality: 4.8,
    brandSafety: 4.9,
    pricePerPost: 22000,
    availability: true,
    pastBrands: ['Lakme', 'Maybelline', 'Nykaa'],
    fraudRisk: 0.02,
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    bio: 'Makeup artist sharing beauty tips and product reviews.'
  }
];

export const mockBrandCampaigns: BrandCampaign[] = [
  {
    id: 'brand-1',
    brandName: 'TechNova Electronics',
    categories: ['Technology', 'Gadgets', 'Electronics'],
    targetGeo: ['Bangalore', 'Hyderabad', 'Pune', 'Delhi'],
    targetAge: ['25-34', '35-44'],
    targetGenderMix: { male: 70, female: 28, other: 2 },
    minFollowers: 500000,
    minEngagement: 3.5,
    maxPrice: 50000,
    creativesNeeded: 3,
    timeline: '2 weeks',
    brandSafetyMin: 4.5,
    exclusions: ['@competitor_tech'],
    preferredPlatforms: ['YouTube', 'Instagram'],
    budgetCoins: 150000,
    logo: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400',
    description: 'Launch campaign for new smartphone series targeting tech enthusiasts.'
  },
  {
    id: 'brand-2',
    brandName: 'FitLife Nutrition',
    categories: ['Fitness', 'Health', 'Wellness', 'Nutrition'],
    targetGeo: ['Mumbai', 'Delhi', 'Bangalore', 'Chennai'],
    targetAge: ['18-24', '25-34', '35-44'],
    targetGenderMix: { male: 50, female: 48, other: 2 },
    minFollowers: 200000,
    minEngagement: 4.0,
    maxPrice: 25000,
    creativesNeeded: 5,
    timeline: '1 month',
    brandSafetyMin: 4.8,
    exclusions: [],
    preferredPlatforms: ['Instagram', 'YouTube'],
    budgetCoins: 125000,
    logo: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400',
    description: 'Promote our new protein supplement line to fitness enthusiasts.'
  },
  {
    id: 'brand-3',
    brandName: 'Glamour Cosmetics',
    categories: ['Beauty', 'Makeup', 'Skincare'],
    targetGeo: ['Delhi', 'Mumbai', 'Bangalore', 'Jaipur'],
    targetAge: ['18-24', '25-34'],
    targetGenderMix: { male: 10, female: 88, other: 2 },
    minFollowers: 300000,
    minEngagement: 4.5,
    maxPrice: 30000,
    creativesNeeded: 4,
    timeline: '3 weeks',
    brandSafetyMin: 4.7,
    exclusions: [],
    preferredPlatforms: ['Instagram', 'YouTube'],
    budgetCoins: 120000,
    logo: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400',
    description: 'New makeup collection launch targeting young women.'
  },
  {
    id: 'brand-4',
    brandName: 'Urban Threads Fashion',
    categories: ['Fashion', 'Lifestyle', 'Apparel'],
    targetGeo: ['Mumbai', 'Delhi', 'Bangalore', 'Kolkata'],
    targetAge: ['18-24', '25-34'],
    targetGenderMix: { male: 30, female: 68, other: 2 },
    minFollowers: 400000,
    minEngagement: 4.0,
    maxPrice: 35000,
    creativesNeeded: 6,
    timeline: '1 month',
    brandSafetyMin: 4.5,
    exclusions: [],
    preferredPlatforms: ['Instagram', 'TikTok'],
    budgetCoins: 210000,
    logo: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=400',
    description: 'Summer collection showcase for trendy urban fashion.'
  }
];

export const mockInteractions: Interaction[] = [];
